import {chromium} from 'playwright';
import path from 'path';import {fileURLToPath} from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const browser=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1140,height:1000},deviceScaleFactor:2});
const errs=[];page.on('pageerror',e=>errs.push(e.message));
await page.goto('file://'+path.join(__dirname,'report.html'),{waitUntil:'load'});
await page.waitForFunction('window.__DONE__===true',{timeout:15000});
await page.screenshot({path:path.join(__dirname,'mxss-proof.png'),fullPage:true});
console.log('errors:',errs.join('|')||'none');
console.log('screenshot -> mxss-proof.png');
await browser.close();
